/*

 Copyright (c) 2017, Robin Raymond
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 The views and conclusions contained in the software and documentation are those
 of the authors and should not be interpreted as representing official policies,
 either expressed or implied, of the FreeBSD Project.
 
 */

namespace zs
{
  typedef uint64 puid;
  typedef std::list<string> StringList;

  typedef uint64 size_t;

  interface MessageQueue {};

  interface Json
  {
    [getter, setter]
    string value;
  };

  interface Any
  {
  };

  [dictionary]
  struct Milliseconds
  {
    [constructor, default]
    void Milliseconds();

    [constructor, altname(MillisecondsWithValue)]
    void Milliseconds(uint64 count);

    uint64 count;
  };

  [dictionary]
  struct Microseconds
  {
    [constructor, default]
    void Microseconds();

    [constructor, altname(MicrosecondsWithValue)]
    void Microseconds(uint64 count);

    uint64 count;
  };

  [dictionary]
  struct Time
  {
    [constructor]
    void Time();

    [constructor]
    void Time(uint64 millisecondsSinceEpoch);

    [static]
    Time now();

    Milliseconds timeSinceEpoch();
  }

  [special]
  interface Promise
  {
    [getter]
    Any value;

    [getter]
    Any reason;

    [getter]
    Any userData;
  };

  [special]
  template <resultType, reasonType = void>
  interface PromiseWith
  {
    [getter]
    resultType value;

    [getter]
    reasonType reason;

    [getter]
    Any userData;
  };

  namespace exceptions
  {
    [special, exception]
    struct Exception : Any
    {
    };

    [special, exception]
    struct InvalidParameters : Exception
    {
    };

    [special, exception]
    struct InvalidState : Exception
    {
    };

    [special, exception]
    struct NotImplemented : Exception
    {
    };

    [special, exception]
    struct NotSupported : Exception
    {
    };

    [special, exception]
    struct Unexpected : Exception
    {
    };
  }

  namespace log
  {
    enum Level
    {
      None,
      Basic,
      Detail,
      Debug,
      Trace,
      Insane
    };
  }

} // namespace zsLib
